import { Metadata } from 'next';
import photoSrc from '../public/home.jpg'
import Hero from "@/components/hero";

export const metadata: Metadata  = {
  title: "Gallery",
  description: "Generated by create next app",
};

export default function Page( ) {
  return (
    <Hero imgUrl={photoSrc} altText="Home" title="Welcome to the Home Page"/>
  );
}
